#! /usr/bin/env python
#
# GUI module generated by PAGE version 4.9
# In conjunction with Tcl version 8.6
#    Oct 04, 2017 11:16:59 AM
import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

import RNAFinder_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    RNAFinder_support.set_Tk_var()
    top = New_Toplevel_1 (root)
    RNAFinder_support.init(root, top)
    root.mainloop()

w = None
def create_New_Toplevel_1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    RNAFinder_support.set_Tk_var()
    top = New_Toplevel_1 (w)
    RNAFinder_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_New_Toplevel_1():
    global w
    w.destroy()
    w = None


class New_Toplevel_1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font9 = "-family {Segoe UI} -size 9 -weight normal -slant "  \
            "roman -underline 0 -overstrike 0"
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("2757x1803+835+127")
        top.title("New Toplevel 1")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")



        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.01, rely=0.59, relheight=0.05
                , relwidth=0.25)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(foreground="black")
        self.Labelframe1.configure(text='''MS method :''')
        self.Labelframe1.configure(background="#d9d9d9")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=700)

        self.Radiobutton2 = Radiobutton(self.Labelframe1)
        self.Radiobutton2.place(relx=0.41, rely=0.42, relheight=0.55
                , relwidth=0.31)
        self.Radiobutton2.configure(activebackground="#d9d9d9")
        self.Radiobutton2.configure(activeforeground="#000000")
        self.Radiobutton2.configure(anchor=W)
        self.Radiobutton2.configure(background="#d9d9d9")
        self.Radiobutton2.configure(command=RNAFinder_support.adductselection)
        self.Radiobutton2.configure(disabledforeground="#a3a3a3")
        self.Radiobutton2.configure(foreground="#000000")
        self.Radiobutton2.configure(highlightbackground="#d9d9d9")
        self.Radiobutton2.configure(highlightcolor="black")
        self.Radiobutton2.configure(justify=LEFT)
        self.Radiobutton2.configure(text='''Negative mode''')
        self.Radiobutton2.configure(value="2")
        self.Radiobutton2.configure(variable=RNAFinder_support.rdo_negmode)

        self.Radiobutton1 = Radiobutton(self.Labelframe1)
        self.Radiobutton1.place(relx=0.04, rely=0.42, relheight=0.55
                , relwidth=0.29)
        self.Radiobutton1.configure(activebackground="#d9d9d9")
        self.Radiobutton1.configure(activeforeground="#000000")
        self.Radiobutton1.configure(anchor=W)
        self.Radiobutton1.configure(background="#d9d9d9")
        self.Radiobutton1.configure(command=RNAFinder_support.adductselection)
        self.Radiobutton1.configure(disabledforeground="#a3a3a3")
        self.Radiobutton1.configure(foreground="#000000")
        self.Radiobutton1.configure(highlightbackground="#d9d9d9")
        self.Radiobutton1.configure(highlightcolor="black")
        self.Radiobutton1.configure(justify=LEFT)
        self.Radiobutton1.configure(text='''Positive mode''')
        self.Radiobutton1.configure(value="1")
        self.Radiobutton1.configure(variable=RNAFinder_support.rdo_posmode)

        self.Labelframe2 = LabelFrame(top)
        self.Labelframe2.place(relx=0.01, rely=0.11, relheight=0.08
                , relwidth=0.25)
        self.Labelframe2.configure(relief=GROOVE)
        self.Labelframe2.configure(foreground="black")
        self.Labelframe2.configure(text='''Phylogenetic Occurrence''')
        self.Labelframe2.configure(background="#d9d9d9")
        self.Labelframe2.configure(highlightbackground="#d9d9d9")
        self.Labelframe2.configure(highlightcolor="black")
        self.Labelframe2.configure(width=700)

        self.Checkbutton1 = Checkbutton(self.Labelframe2)
        self.Checkbutton1.place(relx=0.04, rely=0.28, relheight=0.36
                , relwidth=0.19)
        self.Checkbutton1.configure(activebackground="#d9d9d9")
        self.Checkbutton1.configure(activeforeground="#000000")
        self.Checkbutton1.configure(anchor=W)
        self.Checkbutton1.configure(background="#d9d9d9")
        self.Checkbutton1.configure(command=RNAFinder_support.allrnaselection)
        self.Checkbutton1.configure(disabledforeground="#a3a3a3")
        self.Checkbutton1.configure(font=font9)
        self.Checkbutton1.configure(foreground="#000000")
        self.Checkbutton1.configure(highlightbackground="#d9d9d9")
        self.Checkbutton1.configure(highlightcolor="black")
        self.Checkbutton1.configure(justify=LEFT)
        self.Checkbutton1.configure(text='''Archaeal''')
        self.Checkbutton1.configure(variable=RNAFinder_support.Archaeal)

        self.Checkbutton2 = Checkbutton(self.Labelframe2)
        self.Checkbutton2.place(relx=0.43, rely=0.28, relheight=0.36
                , relwidth=0.19)
        self.Checkbutton2.configure(activebackground="#d9d9d9")
        self.Checkbutton2.configure(activeforeground="#000000")
        self.Checkbutton2.configure(anchor=W)
        self.Checkbutton2.configure(background="#d9d9d9")
        self.Checkbutton2.configure(command=RNAFinder_support.allrnaselection)
        self.Checkbutton2.configure(disabledforeground="#a3a3a3")
        self.Checkbutton2.configure(foreground="#000000")
        self.Checkbutton2.configure(highlightbackground="#d9d9d9")
        self.Checkbutton2.configure(highlightcolor="black")
        self.Checkbutton2.configure(justify=LEFT)
        self.Checkbutton2.configure(text='''Bacterial''')
        self.Checkbutton2.configure(variable=RNAFinder_support.Bacterial)

        self.Checkbutton3 = Checkbutton(self.Labelframe2)
        self.Checkbutton3.place(relx=0.04, rely=0.62, relheight=0.36
                , relwidth=0.32)
        self.Checkbutton3.configure(activebackground="#d9d9d9")
        self.Checkbutton3.configure(activeforeground="#000000")
        self.Checkbutton3.configure(anchor=W)
        self.Checkbutton3.configure(background="#d9d9d9")
        self.Checkbutton3.configure(command=RNAFinder_support.allrnaselection)
        self.Checkbutton3.configure(disabledforeground="#a3a3a3")
        self.Checkbutton3.configure(foreground="#000000")
        self.Checkbutton3.configure(highlightbackground="#d9d9d9")
        self.Checkbutton3.configure(highlightcolor="black")
        self.Checkbutton3.configure(justify=LEFT)
        self.Checkbutton3.configure(text='''Eukaryotic''')
        self.Checkbutton3.configure(variable=RNAFinder_support.Eukaryotic)

        self.Checkbutton4 = Checkbutton(self.Labelframe2)
        self.Checkbutton4.place(relx=0.43, rely=0.62, relheight=0.36
                , relwidth=0.24)
        self.Checkbutton4.configure(activebackground="#d9d9d9")
        self.Checkbutton4.configure(activeforeground="#000000")
        self.Checkbutton4.configure(anchor=W)
        self.Checkbutton4.configure(background="#d9d9d9")
        self.Checkbutton4.configure(command=RNAFinder_support.allrnaselection)
        self.Checkbutton4.configure(disabledforeground="#a3a3a3")
        self.Checkbutton4.configure(foreground="#000000")
        self.Checkbutton4.configure(highlightbackground="#d9d9d9")
        self.Checkbutton4.configure(highlightcolor="black")
        self.Checkbutton4.configure(justify=LEFT)
        self.Checkbutton4.configure(text='''All''')
        self.Checkbutton4.configure(variable=RNAFinder_support.alltrnas)

        self.Labelframe3 = LabelFrame(top)
        self.Labelframe3.place(relx=0.01, rely=0.64, relheight=0.11
                , relwidth=0.25)
        self.Labelframe3.configure(relief=GROOVE)
        self.Labelframe3.configure(foreground="black")
        self.Labelframe3.configure(text='''Adduct ions''')
        self.Labelframe3.configure(background="#d9d9d9")
        self.Labelframe3.configure(highlightbackground="#d9d9d9")
        self.Labelframe3.configure(highlightcolor="black")
        self.Labelframe3.configure(width=700)

        self.Checkbutton5 = Checkbutton(self.Labelframe3)
        self.Checkbutton5.place(relx=0.04, rely=0.24, relheight=0.25
                , relwidth=0.1)
        self.Checkbutton5.configure(activebackground="#d9d9d9")
        self.Checkbutton5.configure(activeforeground="#000000")
        self.Checkbutton5.configure(anchor=W)
        self.Checkbutton5.configure(background="#d9d9d9")
        self.Checkbutton5.configure(disabledforeground="#a3a3a3")
        self.Checkbutton5.configure(foreground="#000000")
        self.Checkbutton5.configure(highlightbackground="#d9d9d9")
        self.Checkbutton5.configure(highlightcolor="black")
        self.Checkbutton5.configure(justify=LEFT)
        self.Checkbutton5.configure(text='''H+''')
        self.Checkbutton5.configure(variable=RNAFinder_support.Hplus)

        self.Checkbutton6 = Checkbutton(self.Labelframe3)
        self.Checkbutton6.place(relx=0.2, rely=0.24, relheight=0.25
                , relwidth=0.07)
        self.Checkbutton6.configure(activebackground="#d9d9d9")
        self.Checkbutton6.configure(activeforeground="#000000")
        self.Checkbutton6.configure(anchor=W)
        self.Checkbutton6.configure(background="#d9d9d9")
        self.Checkbutton6.configure(disabledforeground="#a3a3a3")
        self.Checkbutton6.configure(foreground="#000000")
        self.Checkbutton6.configure(highlightbackground="#d9d9d9")
        self.Checkbutton6.configure(highlightcolor="black")
        self.Checkbutton6.configure(justify=LEFT)
        self.Checkbutton6.configure(text='''+''')
        self.Checkbutton6.configure(variable=RNAFinder_support.plus)

        self.Checkbutton7 = Checkbutton(self.Labelframe3)
        self.Checkbutton7.place(relx=0.34, rely=0.24, relheight=0.25
                , relwidth=0.12)
        self.Checkbutton7.configure(activebackground="#d9d9d9")
        self.Checkbutton7.configure(activeforeground="#000000")
        self.Checkbutton7.configure(anchor=W)
        self.Checkbutton7.configure(background="#d9d9d9")
        self.Checkbutton7.configure(disabledforeground="#a3a3a3")
        self.Checkbutton7.configure(foreground="#000000")
        self.Checkbutton7.configure(highlightbackground="#d9d9d9")
        self.Checkbutton7.configure(highlightcolor="black")
        self.Checkbutton7.configure(justify=LEFT)
        self.Checkbutton7.configure(text='''Na+''')
        self.Checkbutton7.configure(variable=RNAFinder_support.Naplus)

        self.Checkbutton8 = Checkbutton(self.Labelframe3)
        self.Checkbutton8.place(relx=0.51, rely=0.24, relheight=0.25
                , relwidth=0.15)
        self.Checkbutton8.configure(activebackground="#d9d9d9")
        self.Checkbutton8.configure(activeforeground="#000000")
        self.Checkbutton8.configure(anchor=W)
        self.Checkbutton8.configure(background="#d9d9d9")
        self.Checkbutton8.configure(disabledforeground="#a3a3a3")
        self.Checkbutton8.configure(foreground="#000000")
        self.Checkbutton8.configure(highlightbackground="#d9d9d9")
        self.Checkbutton8.configure(highlightcolor="black")
        self.Checkbutton8.configure(justify=LEFT)
        self.Checkbutton8.configure(text='''NH4+''')
        self.Checkbutton8.configure(variable=RNAFinder_support.NH4plus)

        self.Checkbutton9 = Checkbutton(self.Labelframe3)
        self.Checkbutton9.place(relx=0.04, rely=0.49, relheight=0.25
                , relwidth=0.1)
        self.Checkbutton9.configure(activebackground="#d9d9d9")
        self.Checkbutton9.configure(activeforeground="#000000")
        self.Checkbutton9.configure(anchor=W)
        self.Checkbutton9.configure(background="#d9d9d9")
        self.Checkbutton9.configure(disabledforeground="#a3a3a3")
        self.Checkbutton9.configure(foreground="#000000")
        self.Checkbutton9.configure(highlightbackground="#d9d9d9")
        self.Checkbutton9.configure(highlightcolor="black")
        self.Checkbutton9.configure(justify=LEFT)
        self.Checkbutton9.configure(text='''K+''')
        self.Checkbutton9.configure(variable=RNAFinder_support.Kplus)

        self.Checkbutton10 = Checkbutton(self.Labelframe3)
        self.Checkbutton10.place(relx=0.2, rely=0.49, relheight=0.25
                , relwidth=0.22)
        self.Checkbutton10.configure(activebackground="#d9d9d9")
        self.Checkbutton10.configure(activeforeground="#000000")
        self.Checkbutton10.configure(anchor=W)
        self.Checkbutton10.configure(background="#d9d9d9")
        self.Checkbutton10.configure(disabledforeground="#a3a3a3")
        self.Checkbutton10.configure(foreground="#000000")
        self.Checkbutton10.configure(highlightbackground="#d9d9d9")
        self.Checkbutton10.configure(highlightcolor="black")
        self.Checkbutton10.configure(justify=LEFT)
        self.Checkbutton10.configure(text='''-H2O+H+''')
        self.Checkbutton10.configure(variable=RNAFinder_support.H2OplusHplus)

        self.Checkbutton11 = Checkbutton(self.Labelframe3)
        self.Checkbutton11.place(relx=0.49, rely=0.49, relheight=0.25
                , relwidth=0.2)
        self.Checkbutton11.configure(activebackground="#d9d9d9")
        self.Checkbutton11.configure(activeforeground="#000000")
        self.Checkbutton11.configure(anchor=W)
        self.Checkbutton11.configure(background="#d9d9d9")
        self.Checkbutton11.configure(disabledforeground="#a3a3a3")
        self.Checkbutton11.configure(foreground="#000000")
        self.Checkbutton11.configure(highlightbackground="#d9d9d9")
        self.Checkbutton11.configure(highlightcolor="black")
        self.Checkbutton11.configure(justify=LEFT)
        self.Checkbutton11.configure(text='''C2H4N+''')
        self.Checkbutton11.configure(variable=RNAFinder_support.C2H4Nplus)

        self.Checkbutton12 = Checkbutton(self.Labelframe3)
        self.Checkbutton12.place(relx=0.7, rely=0.49, relheight=0.25
                , relwidth=0.27)
        self.Checkbutton12.configure(activebackground="#d9d9d9")
        self.Checkbutton12.configure(activeforeground="#000000")
        self.Checkbutton12.configure(anchor=W)
        self.Checkbutton12.configure(background="#d9d9d9")
        self.Checkbutton12.configure(disabledforeground="#a3a3a3")
        self.Checkbutton12.configure(foreground="#000000")
        self.Checkbutton12.configure(highlightbackground="#d9d9d9")
        self.Checkbutton12.configure(highlightcolor="black")
        self.Checkbutton12.configure(justify=LEFT)
        self.Checkbutton12.configure(text='''C2H3N1Na+''')
        self.Checkbutton12.configure(variable=RNAFinder_support.C2H3N1Naplus)

        self.Checkbutton13 = Checkbutton(self.Labelframe3)
        self.Checkbutton13.place(relx=0.69, rely=0.24, relheight=0.25
                , relwidth=0.27)
        self.Checkbutton13.configure(activebackground="#d9d9d9")
        self.Checkbutton13.configure(activeforeground="#000000")
        self.Checkbutton13.configure(anchor=W)
        self.Checkbutton13.configure(background="#d9d9d9")
        self.Checkbutton13.configure(disabledforeground="#a3a3a3")
        self.Checkbutton13.configure(foreground="#000000")
        self.Checkbutton13.configure(highlightbackground="#d9d9d9")
        self.Checkbutton13.configure(highlightcolor="black")
        self.Checkbutton13.configure(justify=LEFT)
        self.Checkbutton13.configure(text='''Pt(NH3)n(2+)''')
        self.Checkbutton13.configure(variable=RNAFinder_support.Ptplus)

        self.Checkbutton26 = Checkbutton(self.Labelframe3)
        self.Checkbutton26.place(relx=0.04, rely=0.73, relheight=0.25
                , relwidth=0.09)
        self.Checkbutton26.configure(activebackground="#d9d9d9")
        self.Checkbutton26.configure(activeforeground="#000000")
        self.Checkbutton26.configure(anchor=W)
        self.Checkbutton26.configure(background="#d9d9d9")
        self.Checkbutton26.configure(disabledforeground="#a3a3a3")
        self.Checkbutton26.configure(foreground="#000000")
        self.Checkbutton26.configure(highlightbackground="#d9d9d9")
        self.Checkbutton26.configure(highlightcolor="black")
        self.Checkbutton26.configure(justify=LEFT)
        self.Checkbutton26.configure(state=DISABLED)
        self.Checkbutton26.configure(text='''H-''')
        self.Checkbutton26.configure(variable=RNAFinder_support.Hminus)

        self.Checkbutton27 = Checkbutton(self.Labelframe3)
        self.Checkbutton27.place(relx=0.2, rely=0.73, relheight=0.25
                , relwidth=0.06)
        self.Checkbutton27.configure(activebackground="#d9d9d9")
        self.Checkbutton27.configure(activeforeground="#000000")
        self.Checkbutton27.configure(anchor=W)
        self.Checkbutton27.configure(background="#d9d9d9")
        self.Checkbutton27.configure(disabledforeground="#a3a3a3")
        self.Checkbutton27.configure(foreground="#000000")
        self.Checkbutton27.configure(highlightbackground="#d9d9d9")
        self.Checkbutton27.configure(highlightcolor="black")
        self.Checkbutton27.configure(justify=LEFT)
        self.Checkbutton27.configure(state=DISABLED)
        self.Checkbutton27.configure(text='''-''')
        self.Checkbutton27.configure(variable=RNAFinder_support.minus)

        self.Checkbutton28 = Checkbutton(self.Labelframe3)
        self.Checkbutton28.place(relx=0.36, rely=0.73, relheight=0.25
                , relwidth=0.1)
        self.Checkbutton28.configure(activebackground="#d9d9d9")
        self.Checkbutton28.configure(activeforeground="#000000")
        self.Checkbutton28.configure(background="#d9d9d9")
        self.Checkbutton28.configure(disabledforeground="#a3a3a3")
        self.Checkbutton28.configure(foreground="#000000")
        self.Checkbutton28.configure(highlightbackground="#d9d9d9")
        self.Checkbutton28.configure(highlightcolor="black")
        self.Checkbutton28.configure(justify=LEFT)
        self.Checkbutton28.configure(state=DISABLED)
        self.Checkbutton28.configure(text='''Cl-''')
        self.Checkbutton28.configure(variable=RNAFinder_support.Clminus)

        self.Checkbutton29 = Checkbutton(self.Labelframe3)
        self.Checkbutton29.place(relx=0.51, rely=0.73, relheight=0.25
                , relwidth=0.2)
        self.Checkbutton29.configure(activebackground="#d9d9d9")
        self.Checkbutton29.configure(activeforeground="#000000")
        self.Checkbutton29.configure(background="#d9d9d9")
        self.Checkbutton29.configure(disabledforeground="#a3a3a3")
        self.Checkbutton29.configure(foreground="#000000")
        self.Checkbutton29.configure(highlightbackground="#d9d9d9")
        self.Checkbutton29.configure(highlightcolor="black")
        self.Checkbutton29.configure(justify=LEFT)
        self.Checkbutton29.configure(state=DISABLED)
        self.Checkbutton29.configure(text='''-H2O-H-''')
        self.Checkbutton29.configure(variable=RNAFinder_support.minusH2OHminus)

        self.Checkbutton30 = Checkbutton(self.Labelframe3)
        self.Checkbutton30.place(relx=0.74, rely=0.73, relheight=0.25
                , relwidth=0.2)
        self.Checkbutton30.configure(activebackground="#d9d9d9")
        self.Checkbutton30.configure(activeforeground="#000000")
        self.Checkbutton30.configure(background="#d9d9d9")
        self.Checkbutton30.configure(disabledforeground="#a3a3a3")
        self.Checkbutton30.configure(foreground="#000000")
        self.Checkbutton30.configure(highlightbackground="#d9d9d9")
        self.Checkbutton30.configure(highlightcolor="black")
        self.Checkbutton30.configure(justify=LEFT)
        self.Checkbutton30.configure(state=DISABLED)
        self.Checkbutton30.configure(text='''-2H+Na-''')
        self.Checkbutton30.configure(variable=RNAFinder_support.H2Naminus)

        self.Labelframe4 = LabelFrame(top)
        self.Labelframe4.place(relx=0.01, rely=0.52, relheight=0.07
                , relwidth=0.25)
        self.Labelframe4.configure(relief=GROOVE)
        self.Labelframe4.configure(foreground="black")
        self.Labelframe4.configure(text='''CID fragments''')
        self.Labelframe4.configure(background="#d9d9d9")
        self.Labelframe4.configure(highlightbackground="#d9d9d9")
        self.Labelframe4.configure(highlightcolor="black")
        self.Labelframe4.configure(width=700)

        self.Checkbutton14 = Checkbutton(self.Labelframe4)
        self.Checkbutton14.place(relx=0.06, rely=0.24, relheight=0.42
                , relwidth=0.08)
        self.Checkbutton14.configure(activebackground="#d9d9d9")
        self.Checkbutton14.configure(activeforeground="#000000")
        self.Checkbutton14.configure(anchor=W)
        self.Checkbutton14.configure(background="#d9d9d9")
        self.Checkbutton14.configure(disabledforeground="#a3a3a3")
        self.Checkbutton14.configure(foreground="#000000")
        self.Checkbutton14.configure(highlightbackground="#d9d9d9")
        self.Checkbutton14.configure(highlightcolor="black")
        self.Checkbutton14.configure(justify=LEFT)
        self.Checkbutton14.configure(text='''w''')
        self.Checkbutton14.configure(variable=RNAFinder_support.wion)

        self.Checkbutton15 = Checkbutton(self.Labelframe4)
        self.Checkbutton15.place(relx=0.3, rely=0.24, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton15.configure(activebackground="#d9d9d9")
        self.Checkbutton15.configure(activeforeground="#000000")
        self.Checkbutton15.configure(anchor=W)
        self.Checkbutton15.configure(background="#d9d9d9")
        self.Checkbutton15.configure(disabledforeground="#a3a3a3")
        self.Checkbutton15.configure(foreground="#000000")
        self.Checkbutton15.configure(highlightbackground="#d9d9d9")
        self.Checkbutton15.configure(highlightcolor="black")
        self.Checkbutton15.configure(justify=LEFT)
        self.Checkbutton15.configure(text='''x''')
        self.Checkbutton15.configure(variable=RNAFinder_support.xion)

        self.Checkbutton16 = Checkbutton(self.Labelframe4)
        self.Checkbutton16.place(relx=0.54, rely=0.24, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton16.configure(activebackground="#d9d9d9")
        self.Checkbutton16.configure(activeforeground="#000000")
        self.Checkbutton16.configure(anchor=W)
        self.Checkbutton16.configure(background="#d9d9d9")
        self.Checkbutton16.configure(disabledforeground="#a3a3a3")
        self.Checkbutton16.configure(foreground="#000000")
        self.Checkbutton16.configure(highlightbackground="#d9d9d9")
        self.Checkbutton16.configure(highlightcolor="black")
        self.Checkbutton16.configure(justify=LEFT)
        self.Checkbutton16.configure(text='''y''')
        self.Checkbutton16.configure(variable=RNAFinder_support.yion)

        self.Checkbutton17 = Checkbutton(self.Labelframe4)
        self.Checkbutton17.place(relx=0.79, rely=0.24, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton17.configure(activebackground="#d9d9d9")
        self.Checkbutton17.configure(activeforeground="#000000")
        self.Checkbutton17.configure(anchor=W)
        self.Checkbutton17.configure(background="#d9d9d9")
        self.Checkbutton17.configure(disabledforeground="#a3a3a3")
        self.Checkbutton17.configure(foreground="#000000")
        self.Checkbutton17.configure(highlightbackground="#d9d9d9")
        self.Checkbutton17.configure(highlightcolor="black")
        self.Checkbutton17.configure(justify=LEFT)
        self.Checkbutton17.configure(text='''z''')
        self.Checkbutton17.configure(variable=RNAFinder_support.zion)

        self.Checkbutton18 = Checkbutton(self.Labelframe4)
        self.Checkbutton18.place(relx=0.06, rely=0.56, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton18.configure(activebackground="#d9d9d9")
        self.Checkbutton18.configure(activeforeground="#000000")
        self.Checkbutton18.configure(anchor=W)
        self.Checkbutton18.configure(background="#d9d9d9")
        self.Checkbutton18.configure(disabledforeground="#a3a3a3")
        self.Checkbutton18.configure(foreground="#000000")
        self.Checkbutton18.configure(highlightbackground="#d9d9d9")
        self.Checkbutton18.configure(highlightcolor="black")
        self.Checkbutton18.configure(justify=LEFT)
        self.Checkbutton18.configure(text='''a''')
        self.Checkbutton18.configure(variable=RNAFinder_support.aion)

        self.Checkbutton19 = Checkbutton(self.Labelframe4)
        self.Checkbutton19.place(relx=0.24, rely=0.56, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton19.configure(activebackground="#d9d9d9")
        self.Checkbutton19.configure(activeforeground="#000000")
        self.Checkbutton19.configure(anchor=W)
        self.Checkbutton19.configure(background="#d9d9d9")
        self.Checkbutton19.configure(disabledforeground="#a3a3a3")
        self.Checkbutton19.configure(foreground="#000000")
        self.Checkbutton19.configure(highlightbackground="#d9d9d9")
        self.Checkbutton19.configure(highlightcolor="black")
        self.Checkbutton19.configure(justify=LEFT)
        self.Checkbutton19.configure(text='''b''')
        self.Checkbutton19.configure(variable=RNAFinder_support.bion)

        self.Checkbutton20 = Checkbutton(self.Labelframe4)
        self.Checkbutton20.place(relx=0.44, rely=0.56, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton20.configure(activebackground="#d9d9d9")
        self.Checkbutton20.configure(activeforeground="#000000")
        self.Checkbutton20.configure(anchor=W)
        self.Checkbutton20.configure(background="#d9d9d9")
        self.Checkbutton20.configure(disabledforeground="#a3a3a3")
        self.Checkbutton20.configure(foreground="#000000")
        self.Checkbutton20.configure(highlightbackground="#d9d9d9")
        self.Checkbutton20.configure(highlightcolor="black")
        self.Checkbutton20.configure(justify=LEFT)
        self.Checkbutton20.configure(text='''c''')
        self.Checkbutton20.configure(variable=RNAFinder_support.cion)

        self.Checkbutton21 = Checkbutton(self.Labelframe4)
        self.Checkbutton21.place(relx=0.61, rely=0.56, relheight=0.42
                , relwidth=0.07)
        self.Checkbutton21.configure(activebackground="#d9d9d9")
        self.Checkbutton21.configure(activeforeground="#000000")
        self.Checkbutton21.configure(anchor=W)
        self.Checkbutton21.configure(background="#d9d9d9")
        self.Checkbutton21.configure(disabledforeground="#a3a3a3")
        self.Checkbutton21.configure(foreground="#000000")
        self.Checkbutton21.configure(highlightbackground="#d9d9d9")
        self.Checkbutton21.configure(highlightcolor="black")
        self.Checkbutton21.configure(justify=LEFT)
        self.Checkbutton21.configure(text='''d''')
        self.Checkbutton21.configure(variable=RNAFinder_support.dion)

        self.Checkbutton31 = Checkbutton(self.Labelframe4)
        self.Checkbutton31.place(relx=0.79, rely=0.56, relheight=0.42
                , relwidth=0.15)
        self.Checkbutton31.configure(activebackground="#d9d9d9")
        self.Checkbutton31.configure(activeforeground="#000000")
        self.Checkbutton31.configure(background="#d9d9d9")
        self.Checkbutton31.configure(disabledforeground="#a3a3a3")
        self.Checkbutton31.configure(foreground="#000000")
        self.Checkbutton31.configure(highlightbackground="#d9d9d9")
        self.Checkbutton31.configure(highlightcolor="black")
        self.Checkbutton31.configure(justify=LEFT)
        self.Checkbutton31.configure(text='''a-B''')
        self.Checkbutton31.configure(variable=RNAFinder_support.aBion)

        self.Labelframe5 = LabelFrame(top)
        self.Labelframe5.place(relx=0.28, rely=0.09, relheight=0.37
                , relwidth=0.67)
        self.Labelframe5.configure(relief=GROOVE)
        self.Labelframe5.configure(foreground="black")
        self.Labelframe5.configure(text='''Experimental file''')
        self.Labelframe5.configure(background="#d9d9d9")
        self.Labelframe5.configure(highlightbackground="#d9d9d9")
        self.Labelframe5.configure(highlightcolor="black")
        self.Labelframe5.configure(width=1850)

        self.Button1 = Button(self.Labelframe5)
        self.Button1.place(relx=0.01, rely=0.09, height=40, width=200)
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(anchor=W)
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(command=RNAFinder_support.uploadfiles)
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(justify=LEFT)
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Upload files >>''')
        self.Button1.bind('<Button-1>',lambda e:RNAFinder_support.xxx(e))

        self.Scrolledlistbox1 = ScrolledListBox(self.Labelframe5)
        self.Scrolledlistbox1.place(relx=0.01, rely=0.21, relheight=0.58
                , relwidth=0.33)
        self.Scrolledlistbox1.configure(background="white")
        self.Scrolledlistbox1.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox1.configure(font="TkFixedFont")
        self.Scrolledlistbox1.configure(foreground="black")
        self.Scrolledlistbox1.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox1.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox1.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox1.configure(selectforeground="black")
        self.Scrolledlistbox1.configure(width=10)

        self.Button2 = Button(self.Labelframe5)
        self.Button2.place(relx=0.38, rely=0.43, height=40, width=170)
        self.Button2.configure(activebackground="#d9d9d9")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(anchor=W)
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(command=RNAFinder_support.Read_mzMLfile)
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(justify=LEFT)
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Plot file >>''')

        self.Canvas1 = Canvas(self.Labelframe5)
        self.Canvas1.place(relx=0.51, rely=0.09, relheight=0.7, relwidth=0.46)
        self.Canvas1.configure(background="white")
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(highlightbackground="#d9d9d9")
        self.Canvas1.configure(highlightcolor="black")
        self.Canvas1.configure(insertbackground="black")
        self.Canvas1.configure(relief=RIDGE)
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(selectforeground="black")
        self.Canvas1.configure(width=858)

        self.Labelframe6 = LabelFrame(top)
        self.Labelframe6.place(relx=0.28, rely=0.01, relheight=0.07
                , relwidth=0.26)
        self.Labelframe6.configure(relief=GROOVE)
        self.Labelframe6.configure(foreground="black")
        self.Labelframe6.configure(text='''Parameters''')
        self.Labelframe6.configure(background="#d9d9d9")
        self.Labelframe6.configure(highlightbackground="#d9d9d9")
        self.Labelframe6.configure(highlightcolor="black")
        self.Labelframe6.configure(width=710)

        self.Label1 = Label(self.Labelframe6)
        self.Label1.place(relx=0.04, rely=0.3, height=51, width=354)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(anchor=W)
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(justify=LEFT)
        self.Label1.configure(text='''M/Z variation window (ppm)''')

        self.Entry1 = Entry(self.Labelframe6)
        self.Entry1.place(relx=0.56, rely=0.37, relheight=0.38, relwidth=0.22)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Button3 = Button(top)
        self.Button3.place(relx=0.28, rely=0.4, height=63, width=142)
        self.Button3.configure(activebackground="#d9d9d9")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(command=RNAFinder_support.processdata)
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(justify=LEFT)
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Process''')

        self.menubar = Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)



        self.Labelframe7 = LabelFrame(top)
        self.Labelframe7.place(relx=0.01, rely=0.46, relheight=0.05
                , relwidth=0.25)
        self.Labelframe7.configure(relief=GROOVE)
        self.Labelframe7.configure(foreground="black")
        self.Labelframe7.configure(text='''Enzyme selection''')
        self.Labelframe7.configure(background="#d9d9d9")
        self.Labelframe7.configure(highlightbackground="#d9d9d9")
        self.Labelframe7.configure(highlightcolor="black")
        self.Labelframe7.configure(width=700)

        self.Radiobutton3 = Radiobutton(self.Labelframe7)
        self.Radiobutton3.place(relx=0.04, rely=0.39, relheight=0.55
                , relwidth=0.15)
        self.Radiobutton3.configure(activebackground="#d9d9d9")
        self.Radiobutton3.configure(activeforeground="#000000")
        self.Radiobutton3.configure(anchor=W)
        self.Radiobutton3.configure(background="#d9d9d9")
        self.Radiobutton3.configure(disabledforeground="#a3a3a3")
        self.Radiobutton3.configure(foreground="#000000")
        self.Radiobutton3.configure(highlightbackground="#d9d9d9")
        self.Radiobutton3.configure(highlightcolor="black")
        self.Radiobutton3.configure(justify=LEFT)
        self.Radiobutton3.configure(text='''T1''')
        self.Radiobutton3.configure(value="1")
        self.Radiobutton3.configure(variable=RNAFinder_support.T1_enzyme)

        self.Radiobutton4 = Radiobutton(self.Labelframe7)
        self.Radiobutton4.place(relx=0.44, rely=0.39, relheight=0.55
                , relwidth=0.15)
        self.Radiobutton4.configure(activebackground="#d9d9d9")
        self.Radiobutton4.configure(activeforeground="#000000")
        self.Radiobutton4.configure(anchor=W)
        self.Radiobutton4.configure(background="#d9d9d9")
        self.Radiobutton4.configure(disabledforeground="#a3a3a3")
        self.Radiobutton4.configure(foreground="#000000")
        self.Radiobutton4.configure(highlightbackground="#d9d9d9")
        self.Radiobutton4.configure(highlightcolor="black")
        self.Radiobutton4.configure(justify=LEFT)
        self.Radiobutton4.configure(text='''A''')
        self.Radiobutton4.configure(value="2")
        self.Radiobutton4.configure(variable=RNAFinder_support.A_enzyme)

        self.Labelframe8 = LabelFrame(top)
        self.Labelframe8.place(relx=0.01, rely=0.76, relheight=0.22
                , relwidth=0.25)
        self.Labelframe8.configure(relief=GROOVE)
        self.Labelframe8.configure(foreground="black")
        self.Labelframe8.configure(text='''Modification''')
        self.Labelframe8.configure(background="#d9d9d9")
        self.Labelframe8.configure(highlightbackground="#d9d9d9")
        self.Labelframe8.configure(highlightcolor="black")
        self.Labelframe8.configure(width=700)

        self.Scrolledlistbox4 = ScrolledListBox(self.Labelframe8)
        self.Scrolledlistbox4.place(relx=0.03, rely=0.1, relheight=0.87
                , relwidth=0.29)
        self.Scrolledlistbox4.configure(background="white")
        self.Scrolledlistbox4.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox4.configure(font="TkFixedFont")
        self.Scrolledlistbox4.configure(foreground="black")
        self.Scrolledlistbox4.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox4.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox4.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox4.configure(selectforeground="black")
        self.Scrolledlistbox4.configure(width=10)

        self.Scrolledlistbox5 = ScrolledListBox(self.Labelframe8)
        self.Scrolledlistbox5.place(relx=0.63, rely=0.1, relheight=0.87
                , relwidth=0.3)
        self.Scrolledlistbox5.configure(background="white")
        self.Scrolledlistbox5.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox5.configure(font="TkFixedFont")
        self.Scrolledlistbox5.configure(foreground="black")
        self.Scrolledlistbox5.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox5.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox5.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox5.configure(selectforeground="black")
        self.Scrolledlistbox5.configure(width=10)

        self.Button4 = Button(self.Labelframe8)
        self.Button4.place(relx=0.37, rely=0.28, height=43, width=156)
        self.Button4.configure(activebackground="#d9d9d9")
        self.Button4.configure(activeforeground="#000000")
        self.Button4.configure(background="#d9d9d9")
        self.Button4.configure(command=RNAFinder_support.selectmodification)
        self.Button4.configure(disabledforeground="#a3a3a3")
        self.Button4.configure(foreground="#000000")
        self.Button4.configure(highlightbackground="#d9d9d9")
        self.Button4.configure(highlightcolor="black")
        self.Button4.configure(justify=LEFT)
        self.Button4.configure(pady="0")
        self.Button4.configure(text='''Select >>''')

        self.Button5 = Button(self.Labelframe8)
        self.Button5.place(relx=0.37, rely=0.61, height=43, width=162)
        self.Button5.configure(activebackground="#d9d9d9")
        self.Button5.configure(activeforeground="#000000")
        self.Button5.configure(background="#d9d9d9")
        self.Button5.configure(command=RNAFinder_support.removemodification)
        self.Button5.configure(disabledforeground="#a3a3a3")
        self.Button5.configure(foreground="#000000")
        self.Button5.configure(highlightbackground="#d9d9d9")
        self.Button5.configure(highlightcolor="black")
        self.Button5.configure(justify=LEFT)
        self.Button5.configure(pady="0")
        self.Button5.configure(text='''<< Remove''')

        self.Labelframe9 = LabelFrame(top)
        self.Labelframe9.place(relx=0.01, rely=0.37, relheight=0.09
                , relwidth=0.25)
        self.Labelframe9.configure(relief=GROOVE)
        self.Labelframe9.configure(foreground="black")
        self.Labelframe9.configure(text='''Base type''')
        self.Labelframe9.configure(background="#d9d9d9")
        self.Labelframe9.configure(highlightbackground="#d9d9d9")
        self.Labelframe9.configure(highlightcolor="black")
        self.Labelframe9.configure(width=700)

        self.Checkbutton22 = Checkbutton(self.Labelframe9)
        self.Checkbutton22.place(relx=0.06, rely=0.26, relheight=0.34
                , relwidth=0.09)
        self.Checkbutton22.configure(activebackground="#d9d9d9")
        self.Checkbutton22.configure(activeforeground="#000000")
        self.Checkbutton22.configure(anchor=W)
        self.Checkbutton22.configure(background="#d9d9d9")
        self.Checkbutton22.configure(disabledforeground="#a3a3a3")
        self.Checkbutton22.configure(foreground="#000000")
        self.Checkbutton22.configure(highlightbackground="#d9d9d9")
        self.Checkbutton22.configure(highlightcolor="black")
        self.Checkbutton22.configure(justify=LEFT)
        self.Checkbutton22.configure(text='''All''')
        self.Checkbutton22.configure(variable=RNAFinder_support.allbase)

        self.Checkbutton23 = Checkbutton(self.Labelframe9)
        self.Checkbutton23.place(relx=0.31, rely=0.26, relheight=0.34
                , relwidth=0.24)
        self.Checkbutton23.configure(activebackground="#d9d9d9")
        self.Checkbutton23.configure(activeforeground="#000000")
        self.Checkbutton23.configure(anchor=W)
        self.Checkbutton23.configure(background="#d9d9d9")
        self.Checkbutton23.configure(disabledforeground="#a3a3a3")
        self.Checkbutton23.configure(foreground="#000000")
        self.Checkbutton23.configure(highlightbackground="#d9d9d9")
        self.Checkbutton23.configure(highlightcolor="black")
        self.Checkbutton23.configure(justify=LEFT)
        self.Checkbutton23.configure(text='''Adenosines''')
        self.Checkbutton23.configure(variable=RNAFinder_support.ABase)

        self.Checkbutton24 = Checkbutton(self.Labelframe9)
        self.Checkbutton24.place(relx=0.66, rely=0.26, relheight=0.34
                , relwidth=0.2)
        self.Checkbutton24.configure(activebackground="#d9d9d9")
        self.Checkbutton24.configure(activeforeground="#000000")
        self.Checkbutton24.configure(anchor=W)
        self.Checkbutton24.configure(background="#d9d9d9")
        self.Checkbutton24.configure(disabledforeground="#a3a3a3")
        self.Checkbutton24.configure(foreground="#000000")
        self.Checkbutton24.configure(highlightbackground="#d9d9d9")
        self.Checkbutton24.configure(highlightcolor="black")
        self.Checkbutton24.configure(justify=LEFT)
        self.Checkbutton24.configure(text='''Cytidines''')
        self.Checkbutton24.configure(variable=RNAFinder_support.CBase)

        self.Checkbutton25 = Checkbutton(self.Labelframe9)
        self.Checkbutton25.place(relx=0.06, rely=0.59, relheight=0.34
                , relwidth=0.24)
        self.Checkbutton25.configure(activebackground="#d9d9d9")
        self.Checkbutton25.configure(activeforeground="#000000")
        self.Checkbutton25.configure(anchor=W)
        self.Checkbutton25.configure(background="#d9d9d9")
        self.Checkbutton25.configure(disabledforeground="#a3a3a3")
        self.Checkbutton25.configure(foreground="#000000")
        self.Checkbutton25.configure(highlightbackground="#d9d9d9")
        self.Checkbutton25.configure(highlightcolor="black")
        self.Checkbutton25.configure(justify=LEFT)
        self.Checkbutton25.configure(text='''Guanosines''')
        self.Checkbutton25.configure(variable=RNAFinder_support.GBase)

        self.Checkbutton32 = Checkbutton(self.Labelframe9)
        self.Checkbutton32.place(relx=0.44, rely=0.57, relheight=0.34
                , relwidth=0.19)
        self.Checkbutton32.configure(activebackground="#d9d9d9")
        self.Checkbutton32.configure(activeforeground="#000000")
        self.Checkbutton32.configure(anchor=W)
        self.Checkbutton32.configure(background="#d9d9d9")
        self.Checkbutton32.configure(disabledforeground="#a3a3a3")
        self.Checkbutton32.configure(foreground="#000000")
        self.Checkbutton32.configure(highlightbackground="#d9d9d9")
        self.Checkbutton32.configure(highlightcolor="black")
        self.Checkbutton32.configure(justify=LEFT)
        self.Checkbutton32.configure(text='''Uridines''')
        self.Checkbutton32.configure(variable=RNAFinder_support.UBase)

        self.Labelframe10 = LabelFrame(top)
        self.Labelframe10.place(relx=0.01, rely=0.01, relheight=0.1
                , relwidth=0.25)
        self.Labelframe10.configure(relief=GROOVE)
        self.Labelframe10.configure(foreground="black")
        self.Labelframe10.configure(text='''RNA Source''')
        self.Labelframe10.configure(background="#d9d9d9")
        self.Labelframe10.configure(highlightbackground="#d9d9d9")
        self.Labelframe10.configure(highlightcolor="black")
        self.Labelframe10.configure(width=700)

        self.Radiobutton5 = Radiobutton(self.Labelframe10)
        self.Radiobutton5.place(relx=0.03, rely=0.29, relheight=0.3
                , relwidth=0.14)
        self.Radiobutton5.configure(activebackground="#d9d9d9")
        self.Radiobutton5.configure(activeforeground="#000000")
        self.Radiobutton5.configure(anchor=W)
        self.Radiobutton5.configure(background="#d9d9d9")
        self.Radiobutton5.configure(disabledforeground="#a3a3a3")
        self.Radiobutton5.configure(foreground="#000000")
        self.Radiobutton5.configure(highlightbackground="#d9d9d9")
        self.Radiobutton5.configure(highlightcolor="black")
        self.Radiobutton5.configure(justify=LEFT)
        self.Radiobutton5.configure(text='''tRNA''')
        self.Radiobutton5.configure(value="1")
        self.Radiobutton5.configure(variable=RNAFinder_support.tRNA)

        self.Radiobutton6 = Radiobutton(self.Labelframe10)
        self.Radiobutton6.place(relx=0.26, rely=0.29, relheight=0.3
                , relwidth=0.14)
        self.Radiobutton6.configure(activebackground="#d9d9d9")
        self.Radiobutton6.configure(activeforeground="#000000")
        self.Radiobutton6.configure(anchor=W)
        self.Radiobutton6.configure(background="#d9d9d9")
        self.Radiobutton6.configure(disabledforeground="#a3a3a3")
        self.Radiobutton6.configure(foreground="#000000")
        self.Radiobutton6.configure(highlightbackground="#d9d9d9")
        self.Radiobutton6.configure(highlightcolor="black")
        self.Radiobutton6.configure(justify=LEFT)
        self.Radiobutton6.configure(text='''rRNA''')
        self.Radiobutton6.configure(value="2")
        self.Radiobutton6.configure(variable=RNAFinder_support.rRNA)

        self.Radiobutton7 = Radiobutton(self.Labelframe10)
        self.Radiobutton7.place(relx=0.46, rely=0.29, relheight=0.3
                , relwidth=0.16)
        self.Radiobutton7.configure(activebackground="#d9d9d9")
        self.Radiobutton7.configure(activeforeground="#000000")
        self.Radiobutton7.configure(anchor=W)
        self.Radiobutton7.configure(background="#d9d9d9")
        self.Radiobutton7.configure(disabledforeground="#a3a3a3")
        self.Radiobutton7.configure(foreground="#000000")
        self.Radiobutton7.configure(highlightbackground="#d9d9d9")
        self.Radiobutton7.configure(highlightcolor="black")
        self.Radiobutton7.configure(justify=LEFT)
        self.Radiobutton7.configure(text='''mRNA''')
        self.Radiobutton7.configure(value="3")
        self.Radiobutton7.configure(variable=RNAFinder_support.mRNA)

        self.Radiobutton8 = Radiobutton(self.Labelframe10)
        self.Radiobutton8.place(relx=0.67, rely=0.29, relheight=0.3
                , relwidth=0.17)
        self.Radiobutton8.configure(activebackground="#d9d9d9")
        self.Radiobutton8.configure(activeforeground="#000000")
        self.Radiobutton8.configure(anchor=W)
        self.Radiobutton8.configure(background="#d9d9d9")
        self.Radiobutton8.configure(disabledforeground="#a3a3a3")
        self.Radiobutton8.configure(foreground="#000000")
        self.Radiobutton8.configure(highlightbackground="#d9d9d9")
        self.Radiobutton8.configure(highlightcolor="black")
        self.Radiobutton8.configure(justify=LEFT)
        self.Radiobutton8.configure(text='''tmRNA''')
        self.Radiobutton8.configure(value="4")
        self.Radiobutton8.configure(variable=RNAFinder_support.tmRNA)

        self.Radiobutton9 = Radiobutton(self.Labelframe10)
        self.Radiobutton9.place(relx=0.03, rely=0.61, relheight=0.3
                , relwidth=0.16)
        self.Radiobutton9.configure(activebackground="#d9d9d9")
        self.Radiobutton9.configure(activeforeground="#000000")
        self.Radiobutton9.configure(anchor=W)
        self.Radiobutton9.configure(background="#d9d9d9")
        self.Radiobutton9.configure(disabledforeground="#a3a3a3")
        self.Radiobutton9.configure(foreground="#000000")
        self.Radiobutton9.configure(highlightbackground="#d9d9d9")
        self.Radiobutton9.configure(highlightcolor="black")
        self.Radiobutton9.configure(justify=LEFT)
        self.Radiobutton9.configure(text='''snRNA''')
        self.Radiobutton9.configure(value="5")
        self.Radiobutton9.configure(variable=RNAFinder_support.snRNA)

        self.Radiobutton10 = Radiobutton(self.Labelframe10)
        self.Radiobutton10.place(relx=0.26, rely=0.61, relheight=0.3
                , relwidth=0.37)
        self.Radiobutton10.configure(activebackground="#d9d9d9")
        self.Radiobutton10.configure(activeforeground="#000000")
        self.Radiobutton10.configure(anchor=W)
        self.Radiobutton10.configure(background="#d9d9d9")
        self.Radiobutton10.configure(disabledforeground="#a3a3a3")
        self.Radiobutton10.configure(foreground="#000000")
        self.Radiobutton10.configure(highlightbackground="#d9d9d9")
        self.Radiobutton10.configure(highlightcolor="black")
        self.Radiobutton10.configure(justify=LEFT)
        self.Radiobutton10.configure(text='''Chromosomal RNA''')
        self.Radiobutton10.configure(value="6")
        self.Radiobutton10.configure(variable=RNAFinder_support.Chromosomal_RNA)

        self.Radiobutton11 = Radiobutton(self.Labelframe10)
        self.Radiobutton11.place(relx=0.67, rely=0.61, relheight=0.3
                , relwidth=0.15)
        self.Radiobutton11.configure(activebackground="#d9d9d9")
        self.Radiobutton11.configure(activeforeground="#000000")
        self.Radiobutton11.configure(background="#d9d9d9")
        self.Radiobutton11.configure(disabledforeground="#a3a3a3")
        self.Radiobutton11.configure(foreground="#000000")
        self.Radiobutton11.configure(highlightbackground="#d9d9d9")
        self.Radiobutton11.configure(highlightcolor="black")
        self.Radiobutton11.configure(justify=LEFT)
        self.Radiobutton11.configure(text='''None''')
        self.Radiobutton11.configure(value="7")
        self.Radiobutton11.configure(variable=RNAFinder_support.none_rna)

        self.Labelframe11 = LabelFrame(top)
        self.Labelframe11.place(relx=0.28, rely=0.48, relheight=0.5
                , relwidth=0.3)
        self.Labelframe11.configure(relief=GROOVE)
        self.Labelframe11.configure(foreground="black")
        self.Labelframe11.configure(text='''Identification results''')
        self.Labelframe11.configure(background="#d9d9d9")
        self.Labelframe11.configure(highlightbackground="#d9d9d9")
        self.Labelframe11.configure(highlightcolor="black")
        self.Labelframe11.configure(width=830)

        self.Labelframe12 = LabelFrame(top)
        self.Labelframe12.place(relx=0.01, rely=0.19, relheight=0.17
                , relwidth=0.25)
        self.Labelframe12.configure(relief=GROOVE)
        self.Labelframe12.configure(foreground="black")
        self.Labelframe12.configure(text='''User defined RNA database''')
        self.Labelframe12.configure(background="#d9d9d9")
        self.Labelframe12.configure(highlightbackground="#d9d9d9")
        self.Labelframe12.configure(highlightcolor="black")
        self.Labelframe12.configure(width=700)

        self.Button7 = Button(self.Labelframe12)
        self.Button7.place(relx=0.03, rely=0.13, height=43, width=182)
        self.Button7.configure(activebackground="#d9d9d9")
        self.Button7.configure(activeforeground="#000000")
        self.Button7.configure(background="#d9d9d9")
        self.Button7.configure(command=RNAFinder_support.upload_userdatabase)
        self.Button7.configure(disabledforeground="#a3a3a3")
        self.Button7.configure(foreground="#000000")
        self.Button7.configure(highlightbackground="#d9d9d9")
        self.Button7.configure(highlightcolor="black")
        self.Button7.configure(pady="0")
        self.Button7.configure(text='''Upload files >>''')

        self.Scrolledlistbox3 = ScrolledListBox(self.Labelframe12)
        self.Scrolledlistbox3.place(relx=0.03, rely=0.29, relheight=0.65
                , relwidth=0.32)
        self.Scrolledlistbox3.configure(background="white")
        self.Scrolledlistbox3.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox3.configure(font="TkFixedFont")
        self.Scrolledlistbox3.configure(foreground="black")
        self.Scrolledlistbox3.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox3.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox3.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox3.configure(selectforeground="black")
        self.Scrolledlistbox3.configure(width=10)

        self.Scrolledlistbox6 = ScrolledListBox(self.Labelframe12)
        self.Scrolledlistbox6.place(relx=0.61, rely=0.28, relheight=0.62
                , relwidth=0.32)
        self.Scrolledlistbox6.configure(background="white")
        self.Scrolledlistbox6.configure(disabledforeground="#a3a3a3")
        self.Scrolledlistbox6.configure(font="TkFixedFont")
        self.Scrolledlistbox6.configure(foreground="black")
        self.Scrolledlistbox6.configure(highlightbackground="#d9d9d9")
        self.Scrolledlistbox6.configure(highlightcolor="#d9d9d9")
        self.Scrolledlistbox6.configure(selectbackground="#c4c4c4")
        self.Scrolledlistbox6.configure(selectforeground="black")
        self.Scrolledlistbox6.configure(width=10)

        self.Button8 = Button(self.Labelframe12)
        self.Button8.place(relx=0.39, rely=0.38, height=43, width=146)
        self.Button8.configure(activebackground="#d9d9d9")
        self.Button8.configure(activeforeground="#000000")
        self.Button8.configure(background="#d9d9d9")
        self.Button8.configure(command=RNAFinder_support.selectuserdatabase)
        self.Button8.configure(disabledforeground="#a3a3a3")
        self.Button8.configure(foreground="#000000")
        self.Button8.configure(highlightbackground="#d9d9d9")
        self.Button8.configure(highlightcolor="black")
        self.Button8.configure(pady="0")
        self.Button8.configure(text='''Select >>''')

        self.Button9 = Button(self.Labelframe12)
        self.Button9.place(relx=0.39, rely=0.7, height=43, width=152)
        self.Button9.configure(activebackground="#d9d9d9")
        self.Button9.configure(activeforeground="#000000")
        self.Button9.configure(background="#d9d9d9")
        self.Button9.configure(command=RNAFinder_support.removeuserdatabase)
        self.Button9.configure(disabledforeground="#a3a3a3")
        self.Button9.configure(foreground="#000000")
        self.Button9.configure(highlightbackground="#d9d9d9")
        self.Button9.configure(highlightcolor="black")
        self.Button9.configure(pady="0")
        self.Button9.configure(text='''<< Remove''')

        self.Labelframe13 = LabelFrame(top)
        self.Labelframe13.place(relx=0.6, rely=0.48, relheight=0.5
                , relwidth=0.35)
        self.Labelframe13.configure(relief=GROOVE)
        self.Labelframe13.configure(foreground="black")
        self.Labelframe13.configure(text='''Labelframe''')
        self.Labelframe13.configure(background="#d9d9d9")
        self.Labelframe13.configure(width=960)

        self.Canvas3 = Canvas(self.Labelframe13)
        self.Canvas3.place(relx=0.04, rely=0.12, relheight=0.67, relwidth=0.89)
        self.Canvas3.configure(background="white")
        self.Canvas3.configure(borderwidth="2")
        self.Canvas3.configure(insertbackground="black")
        self.Canvas3.configure(relief=RIDGE)
        self.Canvas3.configure(selectbackground="#c4c4c4")
        self.Canvas3.configure(selectforeground="black")
        self.Canvas3.configure(width=850)

        self.Button6 = Button(self.Labelframe13)
        self.Button6.place(relx=0.34, rely=0.85, height=43, width=185)
        self.Button6.configure(activebackground="#d9d9d9")
        self.Button6.configure(activeforeground="#000000")
        self.Button6.configure(background="#d9d9d9")
        self.Button6.configure(command=RNAFinder_support.editfigure)
        self.Button6.configure(disabledforeground="#a3a3a3")
        self.Button6.configure(foreground="#000000")
        self.Button6.configure(highlightbackground="#d9d9d9")
        self.Button6.configure(highlightcolor="black")
        self.Button6.configure(pady="0")
        self.Button6.configure(text='''Edit figure''')





# The following code is added to facilitate the Scrolled widgets you specified.
class AutoScroll(object):
    '''Configure the scrollbars for a widget.'''

    def __init__(self, master):
        #  Rozen. Added the try-except clauses so that this class
        #  could be used for scrolled entry widget for which vertical
        #  scrolling is not supported. 5/7/14.
        try:
            vsb = ttk.Scrollbar(master, orient='vertical', command=self.yview)
        except:
            pass
        hsb = ttk.Scrollbar(master, orient='horizontal', command=self.xview)

        #self.configure(yscrollcommand=_autoscroll(vsb),
        #    xscrollcommand=_autoscroll(hsb))
        try:
            self.configure(yscrollcommand=self._autoscroll(vsb))
        except:
            pass
        self.configure(xscrollcommand=self._autoscroll(hsb))

        self.grid(column=0, row=0, sticky='nsew')
        try:
            vsb.grid(column=1, row=0, sticky='ns')
        except:
            pass
        hsb.grid(column=0, row=1, sticky='ew')

        master.grid_columnconfigure(0, weight=1)
        master.grid_rowconfigure(0, weight=1)

        # Copy geometry methods of master  (taken from ScrolledText.py)
        if py3:
            methods = Pack.__dict__.keys() | Grid.__dict__.keys() \
                  | Place.__dict__.keys()
        else:
            methods = Pack.__dict__.keys() + Grid.__dict__.keys() \
                  + Place.__dict__.keys()

        for meth in methods:
            if meth[0] != '_' and meth not in ('config', 'configure'):
                setattr(self, meth, getattr(master, meth))

    @staticmethod
    def _autoscroll(sbar):
        '''Hide and show scrollbar as needed.'''
        def wrapped(first, last):
            first, last = float(first), float(last)
            if first <= 0 and last >= 1:
                sbar.grid_remove()
            else:
                sbar.grid()
            sbar.set(first, last)
        return wrapped

    def __str__(self):
        return str(self.master)

def _create_container(func):
    '''Creates a ttk Frame with a given master, and use this new frame to
    place the scrollbars and the widget.'''
    def wrapped(cls, master, **kw):
        container = ttk.Frame(master)
        return func(cls, container, **kw)
    return wrapped

class ScrolledListBox(AutoScroll, Listbox):
    '''A standard Tkinter Text widget with scrollbars that will
    automatically show/hide as needed.'''
    @_create_container
    def __init__(self, master, **kw):
        Listbox.__init__(self, master, **kw)
        AutoScroll.__init__(self, master)

if __name__ == '__main__':
    vp_start_gui()



